alias PetClinic.Repo
alias PetClinic.PetClinicService.Pet
alias PetClinic.PetClinicPetOwner.PetOwner
alias PetClinic.PetClinicExperts.PetHealthExpert
alias PetClinic.PetClinicService.PetType
alias PetClinic.PetClinicService.ExpertSpecialities
alias PetClinic.AppointmentService.Appointment
alias PetClinic.AppointmentService.ExpertSchedule
alias PetClinic.AppointmentService.AppointmentService

import_if_available(Ecto.Changeset)
import_if_available(Ecto.Query)
