alias PetClinic.Repo
alias PetClinic.PetClinicService.Pet
alias PetClinic.PetClinicPetOwner.PetOwner
alias PetClinic.PetClinicExperts.PetHealthExpert
alias PetClinic.PetClinicService.PetType
alias PetClinic.PetClinicService.ExpertSpecialities

import_if_available(Ecto.Changeset)
import_if_available(Ecto.Query)